// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package rdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToCart = `-- name: AddToCart :exec
insert into carts_content(cart_id, product_id) values($1, $2)
`

type AddToCartParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) error {
	_, err := q.db.Exec(ctx, addToCart, arg.CartID, arg.ProductID)
	return err
}

const createCart = `-- name: CreateCart :one
insert into carts(user_id) values($1) returning id, user_id, in_process, ordered_at
`

func (q *Queries) CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InProcess,
		&i.OrderedAt,
	)
	return i, err
}

const deleteFromCart = `-- name: DeleteFromCart :exec
delete from carts_content 
where id in (select id from carts_content c where c.cart_id = $1 and c.product_id = $2 limit 1)
`

type DeleteFromCartParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) DeleteFromCart(ctx context.Context, arg DeleteFromCartParams) error {
	_, err := q.db.Exec(ctx, deleteFromCart, arg.CartID, arg.ProductID)
	return err
}

const finishOrder = `-- name: FinishOrder :exec
update carts set ordered_at = now() where id = $1
`

func (q *Queries) FinishOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, finishOrder, id)
	return err
}

const getCart = `-- name: GetCart :one
select id, user_id, in_process, ordered_at from carts where user_id = $1 and ordered_at is null
`

func (q *Queries) GetCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InProcess,
		&i.OrderedAt,
	)
	return i, err
}

const getCartProducts = `-- name: GetCartProducts :many
select p.id, market_id, title, price, c.id, cart_id, product_id from products p join carts_content c on p.id = c.product_id where c.cart_id = $1
`

type GetCartProductsRow struct {
	ID        uuid.UUID
	MarketID  uuid.UUID
	Title     string
	Price     int
	ID_2      pgtype.Int4
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartProducts(ctx context.Context, cartID uuid.UUID) ([]GetCartProductsRow, error) {
	rows, err := q.db.Query(ctx, getCartProducts, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartProductsRow{}
	for rows.Next() {
		var i GetCartProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.Title,
			&i.Price,
			&i.ID_2,
			&i.CartID,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForOrder = `-- name: GetProductsForOrder :many
select p.id, market_id, p.title, price, c.id, cart_id, product_id, m.id, m.title, api_link from products p join carts_content c on p.id = c.product_id join markets m on p.market_id = m.id where c.cart_id = $1
`

type GetProductsForOrderRow struct {
	ID        uuid.UUID
	MarketID  uuid.UUID
	Title     string
	Price     int
	ID_2      pgtype.Int4
	CartID    uuid.UUID
	ProductID uuid.UUID
	ID_3      uuid.UUID
	Title_2   string
	ApiLink   string
}

func (q *Queries) GetProductsForOrder(ctx context.Context, cartID uuid.UUID) ([]GetProductsForOrderRow, error) {
	rows, err := q.db.Query(ctx, getProductsForOrder, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsForOrderRow{}
	for rows.Next() {
		var i GetProductsForOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.MarketID,
			&i.Title,
			&i.Price,
			&i.ID_2,
			&i.CartID,
			&i.ProductID,
			&i.ID_3,
			&i.Title_2,
			&i.ApiLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderStartProcess = `-- name: OrderStartProcess :exec
update carts set in_process = true where id = $1 and in_process = false
`

func (q *Queries) OrderStartProcess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, orderStartProcess, id)
	return err
}
