// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external.sql

package rdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteProduct = `-- name: DeleteProduct :exec
delete from products where id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const setProduct = `-- name: SetProduct :exec
insert into products(id, market_id, title, price) values($1, $2, $3, $4)
on conflict (id) do 
update set market_id = $2, title = $3, price = $4
`

type SetProductParams struct {
	ID       uuid.UUID
	MarketID uuid.UUID
	Title    string
	Price    int
}

func (q *Queries) SetProduct(ctx context.Context, arg SetProductParams) error {
	_, err := q.db.Exec(ctx, setProduct,
		arg.ID,
		arg.MarketID,
		arg.Title,
		arg.Price,
	)
	return err
}
