// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	InProcess pgtype.Bool
	OrderedAt pgtype.Timestamp
}

type CartsContent struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

type Market struct {
	ID      uuid.UUID
	Title   string
	ApiLink string
}

type Product struct {
	ID       uuid.UUID
	MarketID uuid.UUID
	Title    string
	Price    int
}

type User struct {
	ID uuid.UUID
}
