// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package rdb

import (
	"context"

	"github.com/google/uuid"
)

const getMarkets = `-- name: GetMarkets :many
select id, title, api_link from markets
`

func (q *Queries) GetMarkets(ctx context.Context) ([]Market, error) {
	rows, err := q.db.Query(ctx, getMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Market{}
	for rows.Next() {
		var i Market
		if err := rows.Scan(&i.ID, &i.Title, &i.ApiLink); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductCard = `-- name: GetProductCard :one
select id, market_id, title, price from products where id = $1
`

func (q *Queries) GetProductCard(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductCard, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.MarketID,
		&i.Title,
		&i.Price,
	)
	return i, err
}
